### ISSUE TITLE
UI is not loaded on startup

### ISSUE THREAD

**Issue by toprak** [manami-project/manami#31]
**Manami version:**
3.1.0
**Java version:**
14
**Steps to reproduce:**
just execute the java -jar manami.jar command
**What is the current behavior:**
it stuck `14:37:19.108 [pool-3-thread-1] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries`

**What`is the expected behavior:**
work properly

**Comment by toprak** [comment]
I am using Xubuntu 20.04
I did java -jar manami.jar and waited so long for 4-5 hours.
In terminal it says:
`14:37:18.675 [pool-3-thread-1] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/dead-entries/kitsu.json]
14:37:19.108 [pool-3-thread-1] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries`
and still same.

**Comment by manami-project** [comment]
There are no log messages indicating that the parsing has finished.
That's why I wanted to know whether the UI showed up for you or not.

**Comment by toprak** [comment]
No, UI has not showed up yet.

**Comment by manami-project** [comment]
Okay then that is the actual problem.
Normally the UI would show up instantly. Populating the cache is done in background.

**Comment by manami-project** [comment]
Which jdk/jre are you using? openjdk, adoptopenjdk, oracle, corretto?

**Comment by toprak** [comment]
openjdk-14-headless.

**Comment by toprak** [comment]
I guess its problem about javafx.
tried that: `java --module-path $PATH_TO_FX --add-modules javafx.graphics,javafx.controls,javafx.fxml -jar ~/Downloads/manami.jar`
and get [that](https://pastebin.ubuntu.com/p/stwkBPJBYW/) error.

**Comment by manami-project** [comment]
Thank you for your investigation. That really helped a lot. The cause is the following import:
`com.sun.javafx.PlatformUtil.*`. I will provide a fix that gets rid of the native import.

**Comment by manami-project** [comment]
@toprak Could you test again using version 3.1.1?

**Comment by toprak** [comment]
Still same

**Comment by manami-project** [comment]
It says [here](https://bugs.openjdk.java.net/browse/JDK-8120519?focusedCommentId=13770406&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13770406) that this is a problem with the setup on the target system.
In [this post](https://stackoverflow.com/a/21203726) is recommended to run the app with `-Dprism.verbose=true` to see which graphics library is missing and then install it. That correlates with the statement in the first link. So based on the first link it seems to me that libgio is missing on your system.

**Comment by toprak** [comment]
Well, tried everything still no work.

**Comment by meitantenik** [comment]
Well that's kinda sad

**Comment by Zuescho** [comment]
Not wanting to revive corpses, but i actually got the same problem:
![cmd_2021-09-13_19-59-08](https://user-images.githubusercontent.com/13680959/133133511-0884ba3e-e217-4bcf-b67a-3da30dbc548b.png)

Using: a fresh installation of openjfx-17_windows-x64_bin-sdk and OpenJDK16U-jdk_x64_windows_hotspot_16.0.2_7 on Windows 10 20H2

**Comment by toprak** [comment]
I had found a solution but I already forgot it :D

**Comment by meitantenik** [comment]
@toprak so there is still hope nice

**Comment by toprak** [comment]
I had used it with bunch of java command with java -jar

**Comment by manami-project** [comment]
Hi @meitantenik,
I agree that previous changes to the jvm/jdk ecosystem were not beneficial in the sense that they cause confusion.
Just saw your comments the other day and wanted to know myself why this was working for me and not for you. So it seems that the build was platform specific. So I added all of the platform specific dependencies in order to produce a multi-platform fatjar. It would be great if you could check the [test build](https://github.com/manami-project/manami/releases/tag/3.3.4-RC) and let me know if it works for you. You should be able to run it with just `java -jar manami.jar`.

**Comment by Zuescho** [comment]
Thanks for the quick fix, just with installed OpenJDK16U-jdk_x64_windows_hotspot_16.0.2_7 it will open right up!
Thanks for the fix!

**Comment by manami-project** [comment]
@Zuescho thank you for testing.
@toprak can you confirm for linux?

**Comment by toprak** [comment]
It works on linux either. Thanks for fixing

**Comment by manami-project** [comment]
@toprak thank you for testing as well.

@Zuescho @toprak : I'll create a proper release. I recommend to use that instead of the test build. The test build will probably create difficulties when changing to a newer version and there won't be a message informing about newer versions.
